using MaderLand.Config.Trample;
using ProtoBuf;

namespace MaderLand.Systems.Trample.Data;

/// <summary>
/// Trample data for single block.
/// </summary>
[ProtoContract]
public class BlockTrampleData
{
    /// <summary>
    /// Current durability of block. Reduced by trampling power. When it reaches 0, block should be fully trampled (replaced with different block).
    /// </summary>
    [ProtoMember(1)]
    public float Durability = 666f;

    /// <summary>
    /// Max durability of block.
    /// </summary>
    [ProtoMember(2)]
    public float MaxDurability = 666f;

    /// <summary>
    /// Regeneration rate of block. Specifies amount of in-game minutes needed for block to regenerate 1 durability point.
    /// </summary>
    [ProtoMember(3)]
    public float Regen = 666f;

    /// <summary>
    /// Default constructor.
    /// </summary>
    public BlockTrampleData()
    {
    }

    /// <summary>
    /// Fills block trample data from config.
    /// </summary>
    /// <param name="cfg">Trample block config data.</param>
    public BlockTrampleData(TrampleBlockCfg cfg)
    {
        Reset(cfg);
    }

    /// <summary>
    /// Resets block trample data from config. Should be used when block is first trampled (when durability is still at max). After that, durability should be reduced by trampling power and regenerated by regen rate.
    /// </summary>
    /// <param name="cfg"></param>
    public void Reset(TrampleBlockCfg cfg)
    {
        Durability = cfg.Durability;
        MaxDurability = cfg.Durability;
        Regen = cfg.Regen;
    }
}
