using MaderLand.Systems.Trample.Config;
using ProtoBuf;

namespace MaderLand.Systems.Trample.Data;

/// <summary>
/// Trample data for single block.
/// </summary>
[ProtoContract]
public class BlockTrampleData
{
    /// <summary>
    /// Current durability of block. Decreased by trampling power, increased by regeneration.
    /// When it reaches 0, block should be fully trampled (usually replaced with different block).
    /// </summary>
    [ProtoMember(1)]
    public float Durability = 0f;

    /// <summary>
    /// Max durability of block.
    /// </summary>
    [ProtoMember(2)]
    public float MaxDurability = 0f;

    /// <summary>
    /// In-game days needed for block to fully regenerate all durability points from zero.
    /// For example, if MaxDurability is 100, current Durability is 25 and Regen is 2.0, it means that block will regenerate 75 durability points in one and half days.
    /// </summary>
    [ProtoMember(3)]
    public float Regen = 0f;

    /// <summary>
    /// In-game days since since creation of the world when that trample data was created/updated.
    /// </summary>
    [ProtoMember(4)]
    public double UpdatedAt = 0d; // 1.0d is one day, so 0.5d is half a day, 0.25d is quarter of a day, etc.

    /// <summary>
    /// Default constructor required by ProtoBuf.
    /// </summary>
    public BlockTrampleData()
    {
    }

    /// <summary>
    /// Fills block trample data from config.
    /// </summary>
    /// <param name="cfg">Trample block config data.</param>
    /// <param name="updatedAt">Current in-game time in days since creation of the world.</param>
    public BlockTrampleData(TrampleBlockCfg cfg, double updatedAt)
    {
        Reset(cfg, updatedAt);
    }

    /// <summary>
    /// Resets block trample data from config. Should be used when block is first trampled (when durability is still at max). After that, durability should be reduced by trampling power and regenerated by regen rate.
    /// </summary>
    /// <param name="cfg"></param>
    /// <param name="updatedAt">Current in-game time in days since creation of the world.</param>
    public void Reset(TrampleBlockCfg cfg, double updatedAt)
    {
        Durability = cfg.Durability;
        MaxDurability = cfg.Durability;
        Regen = cfg.Regen;
        UpdatedAt = updatedAt;
    }
}
